name: lima
description: Aplicatie cu exercitii interactive pentru copii.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Data structures
  stack: ^0.2.1 
  tuple: ^2.0.0

  # State management 
  stacked: ^2.3.13
  stacked_hooks:
  flutter_hooks:

  # Navigation 
  auto_route: 
  stacked_services:

  # Inversion of Control (IoC)
  get_it: 
  injectable:

  # Animation
  animated_text_kit: ^4.2.2
  rive: ^0.9.0
  realm: ^0.4.0+beta
  device_info_plus: ^4.1.2
  flutter_switch: ^0.3.2
  keyboard_event: ^0.3.2

  # Components


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Build Tool
  build_runner:

  # Generators
  auto_route_generator:
  injectable_generator:

flutter:

  uses-material-design: true
  
  fonts: 
    - family: Poppins
      fonts: 
        # THIN
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        # EXTRALIGHT
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        # LIGHT
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        # REGULAR 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

        # MEDIUM
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        # SEMIBOLD
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        # BOLD
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700

        # EXTRABOLD
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
  
        # BLACK
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900 
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

        #
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
